# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Let's Build A Cluster!
email: rick@ucsd.edu
description: This tutorial will show you how to build a cluster using Raspberry Pi's!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SDSC_UCSD
github_username:  SDSC

# Build settings
markdown: redcarpet
